### ISSUE TITLE
[Feature Request] User Friendly Reports

### ISSUE THREAD

**Issue by zero77** [luke-goddard/enumy#27]
enumy finds lots of useful info but, it can some times be a bit hard to analyze when the reports big and there's lots their.

Perhaps, have an option to create an html report with hyperlinks and cullers as well as minimizing or expanding sections, this may make it easier to analyze.
Thanks

**Comment by luke-goddard** [comment]
I agree having a HTML report would be great, it's something that I've wanted to do. I should have some time next week to implement a basic HTML report. I don't really want to invest a lot of time making the report super pretty or anything just functional.
